apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: qyt-lb-ds
spec:
  rules:
  - host: qyt-lb-ds.qytang.com
    http:
      paths:
      - path: /
        backend:
          serviceName: qyt-lb-ds-service
          servicePort: 5000
