{
 "title": "QYT Nameko APP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{container=~\"nameko-.*\"}[$interval]), \"nameko_app_name\", \"$1\", \"container\", \"(nameko-[a-z]+)\")) by (nameko_app_name) * 100",
     "legendFormat": "{{ nameko_app_name }}"
    }
   ]
  },
  {
   "title": "Mem Usage (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{container=~\"nameko-.*\"}, \"nameko_app_name\", \"$1\", \"container\", \"(nameko-[a-z]+)\")) by (nameko_app_name)",
     "legendFormat": "{{nameko_app_name}}"
    }
   ]
  },
  {
   "title": "Network Send Speed (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_network_transmit_bytes_total{namespace='devops',pod=~\"nameko-.*\"}[$interval]), \"nameko_app_name\", \"$1\", \"pod\", \"(nameko-[a-z]+-.*)\")) by (nameko_app_name)\n",
     "legendFormat": "{{nameko_app_name}}"
    }
   ]
  },
  {
   "title": "Network Receive  Speed (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_network_receive_bytes_total{namespace='devops',pod=~\"nameko-.*\"}[$interval]), \"nameko_app_name\", \"$1\", \"pod\", \"(nameko-[a-z]+-.*)\")) by (nameko_app_name)",
     "legendFormat": "{{nameko_app_name}}"
    }
   ]
  }
 ]
}