apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity
  template:
    metadata:
      labels:
        app: affinity
    spec:
      containers:
      - name: affinity
        image: harbor.qytanghost.com/public/nginx_curl
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:  # pod需要的标签
              matchExpressions:
              - key: qytaffinity
                operator: In
                values:
                - qytang
            topologyKey: rack  # Rack需要的标签